/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/finalizar-cadastro` | `/finalizar-cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pre-cadastro` | `/pre-cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar-cadastro` | `/editar-cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pix` | `/pix`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/loan-details/[id]` | `/loan-details/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/analise-proposta/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/payment/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/finalizar-cadastro` | `/finalizar-cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/pre-cadastro` | `/pre-cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/editar-cadastro` | `/editar-cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pix` | `/pix`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/loan-details/[id]` | `/loan-details/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/analise-proposta/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/payment/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/finalizar-cadastro${`?${string}` | `#${string}` | ''}` | `/finalizar-cadastro${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/pre-cadastro${`?${string}` | `#${string}` | ''}` | `/pre-cadastro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/editar-cadastro${`?${string}` | `#${string}` | ''}` | `/editar-cadastro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pix${`?${string}` | `#${string}` | ''}` | `/pix${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/finalizar-cadastro` | `/finalizar-cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/pre-cadastro` | `/pre-cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar-cadastro` | `/editar-cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pix` | `/pix`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/loan-details/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/loan-details/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/analise-proposta/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/payment/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/loan-details/[id]` | `/loan-details/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/analise-proposta/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/payment/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
